<?php

declare(strict_types=1);

namespace SybaseORM\Bundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Define el árbol de configuración del bundle SybaseORM.
 *
 * Soporta dos modos de configuración de conexión:
 * 1. URL única: sybase_orm.connection.url (estilo DATABASE_URL)
 * 2. Parámetros individuales: host, port, database, username, password
 *
 * Cuando se proporciona `url`, los parámetros individuales se ignoran.
 */
final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('sybase_orm');

        /** @var \Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition $rootNode */
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->arrayNode('connection')
                    ->info('Single connection configuration (shorthand for connections.default)')
                    ->children()
                        ->scalarNode('url')
                            ->defaultNull()
                            ->info('URL de conexión completa. Formato: sybase://usuario:password@host:puerto/base_de_datos?charset=UTF-8&persistent=true. Soporta %env(DATABASE_URL)%. Cuando se define, los parámetros individuales (host, port, etc.) se ignoran.')
                        ->end()
                        ->scalarNode('host')
                            ->defaultValue('localhost')
                            ->info('Host del servidor Sybase ASE. Soporta %env(SYBASE_HOST)%.')
                        ->end()
                        ->integerNode('port')
                            ->defaultValue(5000)
                            ->info('Puerto del servidor.')
                        ->end()
                        ->scalarNode('database')
                            ->defaultNull()
                            ->info('Nombre de la base de datos. Soporta %env(SYBASE_DATABASE)%.')
                        ->end()
                        ->scalarNode('username')
                            ->defaultNull()
                            ->info('Usuario de conexión. Soporta %env(SYBASE_USERNAME)%.')
                        ->end()
                        ->scalarNode('password')
                            ->defaultValue('')
                            ->info('Contraseña de conexión. Soporta %env(SYBASE_PASSWORD)%.')
                        ->end()
                        ->scalarNode('charset')
                            ->defaultValue('UTF-8')
                        ->end()
                        ->booleanNode('persistent')
                            ->defaultFalse()
                        ->end()
                        ->booleanNode('charset_conversion')
                            ->defaultFalse()
                            ->info('Habilita conversión transparente UTF-8 ↔ ISO-8859-1.')
                        ->end()
                        ->booleanNode('read_only')
                            ->defaultFalse()
                            ->info('Marca la conexión como solo lectura. Bloquea INSERT/UPDATE/DELETE y transacciones.')
                        ->end()
                    ->end()
                    ->validate()
                        ->ifTrue(function (array $v) {
                            return $v['url'] === null
                                && ($v['database'] === null || $v['username'] === null);
                        })
                        ->thenInvalid('La conexión requiere "url" o los parámetros "database" y "username".')
                    ->end()
                ->end()
                ->arrayNode('connections')
                    ->info('Multiple named connections for multi-database support')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('url')->defaultNull()->end()
                            ->scalarNode('host')->defaultValue('localhost')->end()
                            ->integerNode('port')->defaultValue(5000)->end()
                            ->scalarNode('database')->defaultNull()->end()
                            ->scalarNode('username')->defaultNull()->end()
                            ->scalarNode('password')->defaultValue('')->end()
                            ->scalarNode('charset')->defaultValue('UTF-8')->end()
                            ->booleanNode('persistent')->defaultFalse()->end()
                            ->booleanNode('charset_conversion')->defaultFalse()->end()
                            ->booleanNode('read_only')->defaultFalse()->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('entity_directories')
                    ->scalarPrototype()->end()
                    ->defaultValue(['%kernel.project_dir%/src/Entity'])
                ->end()
                ->scalarNode('proxy_directory')
                    ->defaultValue('%kernel.cache_dir%/sybase_orm/proxies')
                ->end()
                ->scalarNode('migrations_directory')
                    ->defaultValue('%kernel.project_dir%/sybase_ase/migrations')
                ->end()
                ->integerNode('file_permissions')
                    ->defaultValue(0o666)
                    ->info('File permissions for generated proxies and metadata cache (octal).')
                ->end()
                ->integerNode('directory_permissions')
                    ->defaultValue(0o777)
                    ->info('Directory permissions for proxy and cache directories (octal).')
                ->end()
                ->arrayNode('cache')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('adapter')
                            ->defaultNull()
                            ->info('Cache adapter type: "redis" or null. When "redis" is set, the redis node must be configured.')
                        ->end()
                        ->scalarNode('dsn')
                            ->defaultNull()
                            ->info('DSN for the cache adapter (deprecated, use the redis node instead).')
                        ->end()
                        ->integerNode('default_ttl')
                            ->defaultValue(3600)
                            ->info('Default TTL in seconds for second-level cache entries.')
                        ->end()
                        ->scalarNode('prefix')
                            ->defaultValue('sybase_orm:')
                            ->info('Key prefix for Redis cache entries.')
                        ->end()
                        ->integerNode('failure_threshold')
                            ->defaultValue(3)
                            ->info('Number of consecutive failures before disabling second-level cache (circuit breaker).')
                        ->end()
                        ->integerNode('cooldown_seconds')
                            ->defaultValue(60)
                            ->info('Seconds to wait before retrying second-level cache after circuit opens.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('redis')
                    ->addDefaultsIfNotSet()
                    ->info('Redis connection configuration for second-level cache.')
                    ->children()
                        ->scalarNode('host')
                            ->defaultValue('127.0.0.1')
                            ->info('Redis server host. Soporta %env(REDIS_HOST)%.')
                        ->end()
                        ->integerNode('port')
                            ->defaultValue(6379)
                            ->info('Redis server port.')
                        ->end()
                        ->scalarNode('password')
                            ->defaultNull()
                            ->info('Redis authentication password. Soporta %env(REDIS_PASSWORD)%.')
                        ->end()
                        ->integerNode('database')
                            ->defaultValue(0)
                            ->info('Redis database index (0-15).')
                        ->end()
                        ->floatNode('timeout')
                            ->defaultValue(2.0)
                            ->info('Connection timeout in seconds.')
                        ->end()
                        ->scalarNode('dsn')
                            ->defaultNull()
                            ->info('Full Redis DSN (overrides host/port if set). Formato: redis://[:password@]host:port/database')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
