sybase_orm:
    connection:
        url: '%env(DATABASE_URL)%'
    entity_directories:
        - '%kernel.project_dir%/src/Entity'
    proxy_directory: '%kernel.cache_dir%/proxies'
    migrations_directory: '%kernel.project_dir%/migrations'
    cache:
        enabled: false
